name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Using Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x

      - name: Build
        run: npm install && npm run build

      - name: Unit Tests
        run: npm run test
