name: Production Deploy
on:
  push:
    branches:
      - master
jobs:   
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Using Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x

      - name: Build
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: npm install && npm run build && echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.

      - name: Unit Tests
        run: npm run test
