name: Production Deploy
on:
  push:
    branches:
      - feature26/secrets
jobs:   
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Using Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x

      - name: Build
        env:
          VUE_APP_API_KEY: ""
          VUE_APP_AUTH_DOMAIN: ""
          VUE_APP_DATABASE_URL: ""
          VUE_APP_PROJECT_ID: ""
          VUE_APP_STORAGE_BUCKET: ""
          VUE_APP_MESSAGING_SENDER_ID: ""
          VUE_APP_APP_ID: ""
        run: npm install && npm run build && echo $MATOS

      - name: Unit Tests
        run: npm run test
