name: Production Deploy
on:
  push:
    branches:
      - feature26/secrets
jobs:   
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Using Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x

      - name: Build
        env:
          super_secret: ${{ secrets.MATOS }}
        run: npm install && npm run build && touch a.txt && echo $super_secret > a.txt && cat a.txt

      - name: Unit Tests
        run: npm run test
